[package]
name = "timetracker"
version = "2022.6.26"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
clap = "3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
