[package]
name = "activitytracker"
version = "2022.10.31"
edition = "2021"

[dependencies]
clap = "4.0.19"
chrono = "0.4.22"
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
actix-web = "4.2.1"
actix-files = "0.6.2"

