[package]
name = "timetracker"
version = "2022.7.27"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3"
chrono = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
actix-web = "4"
actix-files = "0.6"
diesel = { version = "1.4.8", features = ["postgres"] }
dotenv = "0.15.0"
