# create / start an activity
GET http://localhost:8888/api/start/1st_activity

###

# stop
GET http://localhost:8888/api/stop/1st_activity

###

# stop all
GET http://localhost:8888/api/stopall

###

# check all activities json
GET http://localhost:8888/api/times

###

# Pretty print
GET http://localhost:8888/api/pretty
