name: Rust

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: check formatting
      run: cargo fmt --check

  test:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: run tests
      run: cargo test --verbose
